import { useState } from "react";
import type { ReactElement } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ClipboardList, Plus } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Surface } from "@/components/ui";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { getBankMatchCandidates } from "@/api/bank-reconciliation";
import { approveEmployeeExpenseClaim, assignEmployeeClaimCost, createEmployeeExpenseClaim, listEmployeeExpenseClaims, type EmployeeExpenseClaim } from "@/api/employee-expense-claims";

const KEY = ["employee-expense-claims"] as const;
const rm = (value: string | number) => `RM ${Number(value).toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function EmployeeExpenseClaimsPage() {
  const client = useQueryClient();
  const claims = useQuery({ queryKey: KEY, queryFn: listEmployeeExpenseClaims });
  const candidates = useQuery({ queryKey: ["bank-reconciliation", "candidates"], queryFn: getBankMatchCandidates });
  const [createOpen, setCreateOpen] = useState(false);
  const [assignTarget, setAssignTarget] = useState<EmployeeExpenseClaim | null>(null);
  const refresh = () => client.invalidateQueries({ queryKey: KEY });
  const approve = useMutation({ mutationFn: approveEmployeeExpenseClaim, onSuccess: () => { toast.success("Claim approved and ready for reimbursement."); refresh(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Approval failed") });
  return <div className="space-y-3">
    <PageHeader title="Employee Expense Claims" description="Record employee-paid costs once, approve reimbursement, and attribute shared materials by amount without stock keeping." icon={ClipboardList} actions={<Button variant="gold" onClick={() => setCreateOpen(true)}><Plus className="mr-2 h-4 w-4" />New claim</Button>} />
    <div className="grid gap-2 sm:grid-cols-3">
      <Metric label="Awaiting approval" value={(claims.data ?? []).filter((row) => row.approvalStatus === "submitted").length} />
      <Metric label="Awaiting reimbursement" value={(claims.data ?? []).filter((row) => row.reimbursementStatus === "awaiting_reimbursement" || row.reimbursementStatus === "partial").length} />
      <Metric label="Unallocated shared cost" value={rm((claims.data ?? []).reduce((sum, row) => sum + Number(row.costPurpose === "shared_materials" ? row.unallocatedCost : 0), 0))} />
    </div>
    <Surface className="overflow-hidden p-0"><div className="w-full overflow-x-auto"><table className="w-full table-fixed border-collapse text-[13px] text-[var(--navy-text)]"><colgroup><col className="w-[8%]"/><col className="w-[20%]"/><col className="w-[16%]"/><col className="w-[10%]"/><col className="w-[9%]"/><col className="w-[9%]"/><col className="w-[9%]"/><col className="w-[10%]"/><col className="w-[9%]"/></colgroup><thead className="bg-[var(--table-header)] text-[var(--navy-text)]"><tr>{["Date","Claim / Description","Employee / Supplier","Purpose","Actual Cost","Allocated","Reimbursed","Status","Action"].map((label) => <th key={label} className="border border-[var(--border)] px-2 py-2 text-center text-[13px] font-extrabold leading-tight">{label}</th>)}</tr></thead><tbody>
      {(claims.data ?? []).map((row) => <tr key={row.id} className="bg-white even:bg-[#F3F6F9]"><td className="border border-[var(--border)] px-2 py-2 text-center tabular-nums">{row.expenseDate.slice(0,10)}</td><td className="border border-[var(--border)] px-3 py-2 align-middle"><strong className="block truncate text-sm text-[var(--navy-text)]" title={row.expenseNumber}>{row.expenseNumber}</strong><p className="mt-0.5 line-clamp-2 break-words font-medium leading-5 text-[var(--text-primary)]" title={row.description || "No description"}>{row.description || "No description"}</p></td><td className="border border-[var(--border)] px-3 py-2 align-middle"><b className="block truncate text-sm" title={row.claimantName ?? ""}>{row.claimantName}</b><p className="mt-0.5 truncate text-muted-foreground" title={row.supplierName}>Paid to {row.supplierName}</p></td><td className="border border-[var(--border)] px-2 py-2 text-center leading-5">{row.costPurpose === "unit_specific" ? "Unit-specific" : row.costPurpose === "shared_materials" ? "Shared materials" : "Company overhead"}</td><td className="border border-[var(--border)] px-2 py-2 text-center font-extrabold tabular-nums whitespace-nowrap">{rm(row.totalAmount)}</td><td className="border border-[var(--border)] px-2 py-2 text-center tabular-nums">{row.costPurpose === "shared_materials" ? <><b className="whitespace-nowrap">{rm(row.allocatedCost)}</b><small className="block leading-4 text-amber-800">{rm(row.unallocatedCost)} left</small></> : "—"}</td><td className="border border-[var(--border)] px-2 py-2 text-center font-semibold tabular-nums whitespace-nowrap">{rm(row.reimbursedAmount)}</td><td className="border border-[var(--border)] px-2 py-2 text-center"><Status claim={row} /></td><td className="border border-[var(--border)] px-1 py-2 text-center"><div className="flex flex-col items-stretch justify-center gap-1">{row.approvalStatus === "submitted" && <Button className="h-7 px-2 text-xs" size="sm" onClick={() => approve.mutate(row.id)}>Approve</Button>}{row.approvalStatus === "approved" && row.reimbursementStatus !== "paid" && <Button className="h-7 px-1 text-[11px] leading-tight" size="sm" onClick={() => { window.location.href = `/accounting/bank-reconciliation?claim=${row.id}`; }}>Match bank debit</Button>}{row.costPurpose === "shared_materials" && Number(row.unallocatedCost) > 0 && <Button className="h-7 px-1 text-[11px]" size="sm" variant="outline" onClick={() => setAssignTarget(row)}>Allocate</Button>}</div></td></tr>)}
      {!claims.isLoading && !claims.data?.length && <tr><td colSpan={9} className="px-4 py-12 text-center text-muted-foreground">No employee claims yet.</td></tr>}
    </tbody></table></div></Surface>
    <CreateDialog open={createOpen} apartments={candidates.data?.apartments ?? []} expenses={candidates.data?.expenses ?? []} onClose={() => setCreateOpen(false)} onSaved={() => { refresh(); setCreateOpen(false); }} />
    <AssignDialog claim={assignTarget} apartments={candidates.data?.apartments ?? []} expenses={candidates.data?.expenses ?? []} onClose={() => setAssignTarget(null)} onSaved={() => { refresh(); setAssignTarget(null); }} />
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="flex min-h-14 items-center justify-between rounded-lg border border-[var(--border)] bg-white px-4 py-2 shadow-sm"><span className="text-sm font-medium text-muted-foreground">{label}</span><strong className="ml-3 whitespace-nowrap text-xl text-[var(--navy-text)]">{value}</strong></div>; }
function Status({ claim }: { claim: EmployeeExpenseClaim }) { const text = claim.approvalStatus === "submitted" ? "Awaiting approval" : claim.reimbursementStatus === "paid" ? "Paid" : claim.reimbursementStatus === "partial" ? "Partial" : "Awaiting reimbursement"; const colour = claim.reimbursementStatus === "paid" ? "bg-[#00FF00] text-[#061F38]" : claim.approvalStatus === "submitted" ? "bg-[#FF8C00] text-[#061F38]" : "bg-[#FFFF00] text-[#061F38]"; return <span className={`inline-flex max-w-full justify-center rounded-md px-2 py-1 text-xs font-extrabold leading-tight ${colour}`}>{text}</span>; }

function CreateDialog({ open, apartments, expenses, onClose, onSaved }: { open: boolean; apartments: Array<{id:string;label:string}>; expenses:Array<{id:string;apartmentId:string;periodMonth:string;description:string}>; onClose:()=>void; onSaved:()=>void }) {
  const [claimantName,setClaimantName]=useState(""); const [supplierName,setSupplierName]=useState(""); const [expenseDate,setExpenseDate]=useState(new Date().toISOString().slice(0,10)); const [totalAmount,setTotalAmount]=useState(""); const [description,setDescription]=useState(""); const [costPurpose,setCostPurpose]=useState<EmployeeExpenseClaim["costPurpose"]>("unit_specific"); const [apartmentId,setApartmentId]=useState(""); const [gridExpenseId,setGridExpenseId]=useState("");
  const mutation=useMutation({mutationFn:async()=>{const claim=await createEmployeeExpenseClaim({claimantName,supplierName,expenseDate,totalAmount,description,costPurpose,apartmentId:costPurpose==="unit_specific"?apartmentId||null:null});if(costPurpose==="unit_specific"&&gridExpenseId){await assignEmployeeClaimCost(claim.id,{apartmentId,gridExpenseId,amount:totalAmount,description});}return claim;},onSuccess:()=>{toast.success("Employee claim submitted.");onSaved();},onError:(e)=>toast.error(e instanceof Error?e.message:"Could not create claim")});
  const valid=claimantName&&supplierName&&expenseDate&&Number(totalAmount)>0&&description&&(costPurpose!=="unit_specific"||apartmentId);
  return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>New employee expense claim</DialogTitle><DialogDescription>The employee already paid this cost. Link it to the exact unit charge where possible; reimbursement is later matched to the bank debit.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Field label="Employee name"><input value={claimantName} onChange={(e)=>setClaimantName(e.target.value)} /></Field><Field label="Supplier / Paid to"><input value={supplierName} onChange={(e)=>setSupplierName(e.target.value)} /></Field><Field label="Expense date"><input type="date" value={expenseDate} onChange={(e)=>setExpenseDate(e.target.value)} /></Field><Field label="Actual cost (RM)"><input type="number" min="0.01" step="0.01" value={totalAmount} onChange={(e)=>setTotalAmount(e.target.value)} /></Field><Field label="Cost purpose"><select value={costPurpose} onChange={(e)=>setCostPurpose(e.target.value as EmployeeExpenseClaim["costPurpose"])}><option value="unit_specific">Unit-specific cost</option><option value="shared_materials">Shared materials pool (amount only)</option><option value="company_overhead">Company overhead</option></select></Field>{costPurpose==="unit_specific"&&<><Field label="Unit"><select value={apartmentId} onChange={(e)=>{setApartmentId(e.target.value);setGridExpenseId("");}}><option value="">Select unit</option>{apartments.map((a)=><option key={a.id} value={a.id}>{a.label}</option>)}</select></Field><Field label="Outstanding cost / charge (optional)"><select value={gridExpenseId} onChange={(e)=>setGridExpenseId(e.target.value)}><option value="">No existing charge to link</option>{expenses.filter((item)=>item.apartmentId===apartmentId).map((item)=><option key={item.id} value={item.id}>{item.periodMonth} · {item.description}</option>)}</select></Field></>}<label className="sm:col-span-2 font-semibold">Description<textarea value={description} onChange={(e)=>setDescription(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-3" /></label></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!valid||mutation.isPending} onClick={()=>mutation.mutate()}>Submit claim</Button></DialogFooter></DialogContent></Dialog>;
}
function AssignDialog({ claim,apartments,expenses,onClose,onSaved }:{claim:EmployeeExpenseClaim|null;apartments:Array<{id:string;label:string}>;expenses:Array<{id:string;apartmentId:string;periodMonth:string;description:string}>;onClose:()=>void;onSaved:()=>void}) { const [apartmentId,setApartmentId]=useState("");const [gridExpenseId,setGridExpenseId]=useState("");const [amount,setAmount]=useState("");const [description,setDescription]=useState("");const mutation=useMutation({mutationFn:()=>assignEmployeeClaimCost(claim!.id,{apartmentId,gridExpenseId:gridExpenseId||null,amount,description}),onSuccess:()=>{toast.success("Cost attributed to unit.");onSaved();},onError:(e)=>toast.error(e instanceof Error?e.message:"Could not allocate cost")});return <Dialog open={!!claim} onOpenChange={(v)=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Allocate shared material cost</DialogTitle><DialogDescription>{claim?.expenseNumber} · {rm(claim?.unallocatedCost??0)} remains. This tracks amount only, not stock quantity.</DialogDescription></DialogHeader><Field label="Unit"><select value={apartmentId} onChange={(e)=>{setApartmentId(e.target.value);setGridExpenseId("");}}><option value="">Select unit</option>{apartments.map((a)=><option key={a.id} value={a.id}>{a.label}</option>)}</select></Field><Field label="Related tenant/owner charge (optional)"><select value={gridExpenseId} onChange={(e)=>setGridExpenseId(e.target.value)}><option value="">No charge linked yet</option>{expenses.filter((item)=>item.apartmentId===apartmentId).map((item)=><option key={item.id} value={item.id}>{item.periodMonth} · {item.description}</option>)}</select></Field><Field label="Cost used (RM)"><input type="number" min="0.01" max={claim?.unallocatedCost} step="0.01" value={amount} onChange={(e)=>setAmount(e.target.value)} /></Field><Field label="Usage details"><input value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="e.g. Replace kitchen tap" /></Field><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!apartmentId||Number(amount)<=0||Number(amount)>Number(claim?.unallocatedCost)||mutation.isPending} onClick={()=>mutation.mutate()}>Allocate cost</Button></DialogFooter></DialogContent></Dialog>;}
function Field({label,children}:{label:string;children:ReactElement<{className?:string}>}) { return <label className="block font-semibold">{label}<span className="[&_input]:mt-1 [&_input]:h-11 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:px-3 [&_select]:mt-1 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:px-3">{children}</span></label>; }
